@apimName = <your-api-management-name>
@frontDoorName = <your-frontdoor-name>
@subscriptionKeyConsumer = <your-consumer-subscription-key>

### Test Front door health check for API Management backend
GET http://{{frontDoorName}}.azurefd.net/status-0123456789abcdef

### Test Azure API Management endpoint, with Consumer subscription key (should fail)
GET https://{{apimName}}.azure-api.net/calc/add?a=51&b=49
api-key: {{subscriptionKeyConsumer}}

### Test Front Door endpoint, with Consumer subscription key (should succeed)
GET https://{{frontDoorName}}.azurefd.net/calc/add?a=51&b=49
api-key: {{subscriptionKeyConsumer}}