@apimName = <your-api-management-name>
@frontDoorGwEndpoint = <your-frontdoor-gateway-endpoint>
@subscriptionKeyConsumer = <your-consumer-subscription-key>

### Test Front door health check for API Management Gateway
GET https://{{frontDoorGwEndpoint}}/status-0123456789abcdef

### Test Azure API Management endpoint, with Consumer subscription key (should give 403)
GET https://{{apimName}}.azure-api.net/petstore/pet/findByStatus?status=available
api-key: {{subscriptionKeyConsumer}}

### Test Front Door endpoint, with Consumer subscription key (should succeed)
GET https://{{frontDoorGwEndpoint}}/petstore/pet/findByStatus?status=available
api-key: {{subscriptionKeyConsumer}}